
cc_binary(
    name = 'day01',
    srcs = ['day01.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day02',
    srcs = ['day02.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day03',
    srcs = ['day03.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day04',
    srcs = ['day04.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day05',
    srcs = ['day05.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day07',
    srcs = ['day07.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)

cc_binary(
    name = 'day08',
    srcs = ['day08.cpp'],
    copts = [
        "-pedantic-errors",
        "-Wall",
        "-Wextra",
        "-Werror",
        ],
)
